<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            /*['name' => 'role-list', 'description' => 'View roles'],
           ['name' => 'role-create', 'description' => 'Create new roles'],
           ['name' => 'role-edit', 'description' => 'Edit existing roles'],
           ['name' => 'role-delete', 'description' => 'Delete roles'],
           ['name' => 'product-list', 'description' => 'View products'],
           ['name' => 'product-create', 'description' => 'Create new products'],
           ['name' => 'product-edit', 'description' => 'Edit existing products'],
           ['name' => 'product-delete', 'description' => 'Delete products'],
           ['name' => 'user-list', 'description' => 'View users'],
           ['name' => 'user-create', 'description' => 'Create new users'],
           ['name' => 'user-edit', 'description' => 'Edit existing users'],
           ['name' => 'user-delete', 'description' => 'Delete users'],
           ['name' => 'user-profile', 'description' => 'View user profile'],
           ['name' => 'student-list', 'description' => 'View students'],
           ['name' => 'student-create', 'description' => 'Create new students'],
           ['name' => 'student-edit', 'description' => 'Edit existing students'],
           ['name' => 'student-delete', 'description' => 'Delete students'],
           ['name' => 'staff-list', 'description' => 'View staffs'],
           ['name' => 'staff-create', 'description' => 'Create new staffs'],
           ['name' => 'staff-edit', 'description' => 'Edit existing staffs'],
           ['name' => 'staff-delete', 'description' => 'Delete staffs'],
           ['name' => 'profile-list', 'description' => 'View profile'],
           ['name' => 'profile-create', 'description' => 'Create new profile'],
           ['name' => 'profile-edit', 'description' => 'Edit existing profile'],
           ['name' => 'profile-delete', 'description' => 'Delete profile'],
           ['name' => 'attendance-list', 'description' => 'View attendance'],
           ['name' => 'attendance-create', 'description' => 'Create new attendance'],
           ['name' => 'attendance-edit', 'description' => 'Edit existing attendance'],
           ['name' => 'attendance-delete', 'description' => 'Delete attendance'],
           ['name' => 'department-list', 'description' => 'View departments'],
           ['name' => 'department-create', 'description' => 'Create new departments'],
           ['name' => 'department-edit', 'description' => 'Edit existing departments'],
           ['name' => 'department-delete', 'description' => 'Delete departments'],
           ['name' => 'programme-list', 'description' => 'View programmes'],
           ['name' => 'programme-create', 'description' => 'Create new programmes'],
           ['name' => 'programme-edit', 'description' => 'Edit existing programmes'],
           ['name' => 'programme-delete', 'description' => 'Delete programmes'],
           ['name' => 'course-list', 'description' => 'View courses'],
           ['name' => 'course-create', 'description' => 'Create new courses'],
           ['name' => 'course-edit', 'description' => 'Edit existing courses'],
           ['name' => 'course-delete', 'description' => 'Delete courses'],
           ['name' => 'coursework-list', 'description' => 'View courseworks'],
           ['name' => 'coursework-create', 'description' => 'Create new courseworks'],
           ['name' => 'coursework-edit', 'description' => 'Edit existing courseworks'],
           ['name' => 'coursework-delete', 'description' => 'Delete courseworks'],
           ['name' => 'coursework-config', 'description' => 'Coursework configuration'],
           ['name' => 'semester-exam-list', 'description' => 'View semester examination'],
           ['name' => 'semester-exam-create', 'description' => 'Create new semester examination'],
           ['name' => 'semester-exam-edit', 'description' => 'Edit existing semester examination'],
           ['name' => 'semester-exam-delete', 'description' => 'Delete semester examination'],
           ['name' => 'print-certificate', 'description' => 'Print certificate'],
           ['name' => 'announcement-list', 'description' => 'View announcements'],
           ['name' => 'announcement-create', 'description' => 'Create new announcements'],
           ['name' => 'announcement-edit', 'description' => 'Edit existing announcements'],
           ['name' => 'announcement-delete', 'description' => 'Delete announcements'],
           ['name' => 'download-list', 'description' => 'View downloads'],
           ['name' => 'download-create', 'description' => 'Create new downloads'],
           ['name' => 'download-edit', 'description' => 'Edit existing downloads'],
           ['name' => 'download-delete', 'description' => 'Delete downloads'],
           ['name' => 'hospital-list', 'description' => 'View sick students'],
           ['name' => 'hospital-create', 'description' => 'Create new sick students'],
           ['name' => 'hospital-edit', 'description' => 'Edit existing sick students'],
           ['name' => 'hospital-delete', 'description' => 'Delete sick students'],
           ['name' => 'mps-list', 'description' => 'View lock up'],
           ['name' => 'mps-create', 'description' => 'Create Lock up'],
           ['name' => 'mps-edit', 'description' => 'Modify lock up '],
           ['name' => 'mps-delete', 'description' => 'Delete lock up'],
           ['name' => 'leave-list', 'description' => 'View leave'],
           ['name' => 'leave-create', 'description' => 'Create new leave'],
           ['name' => 'leave-edit', 'description' => 'Edit existing leave'],
           ['name' => 'leave-delete', 'description' => 'Delete leave'],
           ['name' => 'beat-list', 'description' => 'View beats'],
           ['name' => 'beat-create', 'description' => 'Create new beats'],
           ['name' => 'beat-edit', 'description' => 'Edit existing beats'],
           ['name' => 'beat-delete', 'description' => 'Delete beats'],
           ['name' => 'setting-list', 'description' => 'View settings'],
           ['name' => 'setting-create', 'description' => 'Create new settings'],
           ['name' => 'setting-edit', 'description' => 'Edit existing settings'],
           ['name' => 'setting-delete', 'description' => 'Delete settings'],
           ['name' => 'programme-session-list', 'description' => 'View session programme'],
           ['name' => 'programme-session-create', 'description' => 'Create new session programme'],
           ['name' => 'programme-session-edit', 'description' => 'Edit existing session programme'],
           ['name' => 'programme-session-delete', 'description' => 'Delete session programme'],
           ['name' => 'report-list', 'description' => 'View reports'],
           ['name' => 'report-create', 'description' => 'Create new reports'],
           ['name' => 'report-edit', 'description' => 'Edit existing reports'],
           ['name' => 'report-delete', 'description' => 'Delete reports'],
           ['name' => 'enroll-students', 'description' => 'Enroll students to courses'],
           ['name' => 'generate-results', 'description' => 'Generate results Overview'],
           ['name' => 'academic-view', 'description' => 'View Academics'],
           ['name' => 'create-backup', 'description' => 'Create Backup & Restore'],
           ['name' => 'semester-list', 'description' => 'View semesters'],
           ['name' => 'semester-create', 'description' => 'Create new semester'],
           ['name' => 'semester-edit', 'description' => 'Edit existing semester'],
           ['name' => 'semester-delete', 'description' => 'Delete semester'],
           ['name' => 'excuse-type-list', 'description' => 'View excuse types'],
           ['name' => 'excuse-type-create', 'description' => 'Create new excuse types'],
           ['name' => 'excuse-type-edit', 'description' => 'Edit existing excuse types'],
           ['name' => 'excuse-type-delete', 'description' => 'Delete excuse types'],
           ['name' => 'optional-enrollment-list', 'description' => 'View optional enrollments'],
           ['name' => 'optional-enrollment-create', 'description' => 'Create new optional enrollments'],
           ['name' => 'optional-enrollment-edit', 'description' => 'Edit existing optional enrollments'],
           ['name' => 'optional-enrollment-delete', 'description' => 'Delete optional enrollments'],
           ['name' => 'course-enrollment-list', 'description' => 'View course enrollments'],
           ['name' => 'course-enrollment-create', 'description' => 'Create new course enrollments'],
           ['name' => 'course-enrollment-edit', 'description' => 'Edit existing course enrollments'],
           ['name' => 'course-enrollment-delete', 'description' => 'Delete course enrollments'],
           ['name' => 'campus-list', 'description' => 'View campuses'],
           ['name' => 'campus-create', 'description' => 'Create new campus'],
           ['name' => 'campus-edit', 'description' => 'Edit existing campus'],
           ['name' => 'campus-delete', 'description' => 'Delete campus'],
           ['name' => 'hospital-approve', 'description' => 'Approve sick students'],
           ['name' => 'student-courses', 'description' => 'View Courses as Student'],
           ['name' => 'student-coursework-list', 'description' => 'View Courseworks as Student'],
           ['name' => 'staff-view', 'description' => 'View staff profile'],
           /
           ['name' => 'teacher_on_duty-view', 'description' => 'View Teacher On duty'],
           ['name' => 'teacher_on_duty-create', 'description' => 'Create new Teacher On duty'],
           ['name' => 'teacher_on_duty-edit', 'description' => 'Edit Teacher on duty'],
           ['name' => 'teacher_on_duty-delete', 'description' => 'Delete Teacher on duty'],
            
           ['name' => 'post-view', 'description' => 'View Post'],
           ['name' => 'post-create', 'description' => 'Create new Post'],
           ['name' => 'post-edit', 'description' => 'Edit Post'],
           ['name' => 'post-delete', 'description' => 'Delete Post'],
            
            ['name' => 'vitengo-view', 'description' => 'View Vitengo'],
            ['name' => 'vitengo-create', 'description' => 'Create new Kitengo'],
            ['name' => 'vitengo-edit', 'description' => 'Edit Vitengo'],
            ['name' => 'vitengo-delete', 'description' => 'Delete Vitengo'],
            */
            ['name' => 'weapon-view', 'description' => 'List Weapon'],
            ['name' => 'weapon-create', 'description' => 'Create new Weapon'],
            ['name' => 'weapon-edit', 'description' => 'Edit Weapon'],
            ['name' => 'weapon-delete', 'description' => 'Delete Weapon'],            
            // Add other permissions here with descriptions
        ];

        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['name' => $permission['name']], // Match by name
                [
                    'name' => $permission['name'],
                    'description' => $permission['description'],
                ] // Update name & description
            );
        }
    }
}
