<?php

namespace Database\Seeders;
use App\Models\Platoon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlatoonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Platoon::create([
            'company_id'=>'1',
            'name'=>'1'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'2'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'3'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'4'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'5'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'6'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'7'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'8'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'9'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'10'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'11'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'12'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'13'
        ]);
        Platoon::create([
            'company_id'=>'1',
            'name'=>'14'
        ]);


        /**
         * A company platoons
         */

         Platoon::create([
            'company_id'=>'2',
            'name'=>'1'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'2'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'3'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'4'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'5'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'6'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'7'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'8'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'9'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'10'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'11'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'12'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'13'
        ]);
        Platoon::create([
            'company_id'=>'2',
            'name'=>'14'
        ]);



        /**
         * 
         * B Company
         */

         Platoon::create([
            'company_id'=>'3',
            'name'=>'1'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'2'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'3'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'4'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'5'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'6'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'7'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'8'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'9'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'10'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'11'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'12'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'13'
        ]);
        Platoon::create([
            'company_id'=>'3',
            'name'=>'14'
        ]);

        /**
         * C Company
         */

         Platoon::create([
            'company_id'=>'4',
            'name'=>'1'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'2'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'3'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'4'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'5'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'6'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'7'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'8'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'9'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'10'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'11'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'12'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'13'
        ]);
        Platoon::create([
            'company_id'=>'4',
            'name'=>'14'
        ]);
    }
}
